// options.js
const dogBreeds = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akbash Dog",
  "Akita",
  "Alapaha Blue Blood Bulldog",
  "Alaskan Klee Kai",
  "Alaskan Malamute",
  "American Bulldog",
  "American English Coonhound",
  "American Eskimo Dog",
  "American Foxhound",
  "American Hairless Terrier",
  "American Pit Bull Terrier",
  "American Staffordshire Terrier",
  "American Water Spaniel",
  "Anatolian Shepherd Dog",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Australian Terrier",
  "Azawakh",
  "Barbet",
  "Basenji",
  "Basset Fauve De Bretagne",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Belgian Laekenois",
  "Belgian Malinois",
  "Belgian Sheepdog",
  "Belgian Tervuren",
  "Bergamasco Sheepdog",
  "Berger Picard",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Biewer Terrier",
  "Black and Tan Coonhound",
  "Black Mouth Cur",
  "Black Russian Terrier",
  "Bloodhound",
  "Bluetick Coonhound",
  "Boerboel",
  "Bolognese",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier Des Flandres",
  "Boxer",
  "Boykin Spaniel",
  "Bracco Italiano",
  "Briard",
  "Brittany",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Brussels Griffon",
  "Cairn Terrier",
  "Canaan Dog",
  "Canadian Eskimo Dog",
  "Cane Corso",
  "Cardigan Welsh Corgi",
  "Carolina Dog",
  "Caucasian Ovcharka",
  "Cavalier King Charles Spaniel",
  "Central Asian Shepherd Dog",
  "Cesky Terrier",
  "Chart Polski",
  "Chesapeake Bay Retriever",
  "Chinese Crested (hairless)",
  "Chinese Crested (powderpuff)",
  "Chinese Foo Dog",
  "Chinese Shar-Pei",
  "Chinook",
  "Chihuahua",
  "Chow Chow",
  "Cirneco Dell'etna",
  "Clumber Spaniel",
  "Cockapoo",
  "Cocker Spaniel",
  "Collie, Rough",
  "Collie, Smooth",
  "Coton De Tulear",
  "Curly-Coated Retriever",
  "Dachshund, Standard",
  "Dalmatian",
  "Dandie Dinmont Terrier",
  "Doberman Pinscher",
  "Dogo Argentino",
  "Dogue De Bordeaux",
  "Dutch Shepherd",
  "English Cocker Spaniel",
  "English Foxhound",
  "English Setter",
  "English Shepherd",
  "English Springer Spaniel",
  "English Toy Spaniel",
  "Entlebucher Sennenhund",
  "Estrela Mountain Dog",
  "Eurasier",
  "Field Spaniel",
  "Fila Brasileiro",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat-Coated Retriever",
  "Fox Terrier (smooth)",
  "Fox Terrier (wire)",
  "French Bulldog",
  "French Spaniel",
  "German Pinscher",
  "German Shepherd",
  "German Shorthaired Pointer",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Glen Of Imaal Terrier",
  "Golden Retriever",
  "Golden Retriever, Miniature",
  "Goldendoodle",
  "Gordon Setter",
  "Great Dane",
  "Great Pyrenees",
  "Greater Swiss Mountain Dog",
  "Greyhound",
  "Harrier",
  "Havana Silk Dog",
  "Havanese",
  "Hovawart",
  "Ibizan Hound",
  "Icelandic Sheepdog",
  "Irish Red and White Setter",
  "Irish Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Chin",
  "Kangal Dog",
  "Karelian Bear Dog",
  "Keeshond",
  "Kerry Blue Terrier",
  "King Shepherd",
  "Komondor",
  "Kooikerhondje",
  "Kuvasz",
  "Kyi-Leo",
  "Labradoodle",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Lakeland Terrier",
  "Leonberger",
  "Lhasa Apso",
  "Longhaired Whippet",
  "Louisiana Catahoula Leopard Dog",
  "Lowchen",
  "Maltese",
  "Manchester Terrier",
  "Maremma Sheepdog",
  "Mastiff",
  "Mi-Ki",
  "Miniature American Shepherd",
  "Miniature Australian Shepherd",
  "Miniature Bull Terrier",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Neapolitan Mastiff",
  "New Guinea Singing Dog",
  "Newfoundland",
  "Norfolk Terrier",
  "Norrbottenspets",
  "Norwegian Buhund",
  "Norwegian Elkhound",
  "Norwegian Lundehund",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Old English Sheepdog",
  "Olde English Bulldogge",
  "Otterhound",
  "Papillon",
  "Parson Russell Terrier",
  "Patterdale Terrier",
  "Pekingese",
  "Pembroke Welsh Corgi",
  "Perro De Presa Canario",
  "Peruvian Inca Orchid",
  "Petit Basset Griffon Vendeen",
  "Pharaoh Hound",
  "Plott",
  "Pointer",
  "Polish Lowland Sheepdog",
  "Polish Tatra Sheepdog",
  "Pomeranian",
  "Poodle, Miniature",
  "Poodle, Standard",
  "Poodle, Toy",
  "Portuguese Podengo",
  "Portuguese Podengo Pequeno",
  "Portuguese Water Dog",
  "Pug",
  "Puggle",
  "Puli",
  "Pumi",
  "Pyrenean Mastiff",
  "Pyrenean Shepherd",
  "Rat Terrier",
  "Redbone Coonhound",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Russell Terrier",
  "Russian Toy",
  "Russian Tsvetnaya Bolonka",
  "Saint Bernard",
  "Saluki",
  "Samoyed",
  "Sarplaninac",
  "Schapendoes",
  "Schipperke",
  "Schnoodle",
  "Scottish Deerhound",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Seidenspitz",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Shikoku",
  "Shiloh Shepherd",
  "Siberian Husky",
  "Silken Windhound",
  "Silky Terrier",
  "Skye Terrier",
  "Sloughi",
  "Small Munsterlander",
  "Soft Coated Wheaten Terrier",
  "Spanish Water Dog",
  "Spinone Italiano",
  "Stabyhoun",
  "Staffordshire Bull Terrier",
  "Standard Schnauzer",
  "Sussex Spaniel",
  "Swedish Vallhund",
  "Teddy Roosevelt Terrier",
  "Thai Ridgeback",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Tosa Inu-Tosa Ken",
  "Toy Australian Shepherd",
  "Toy Fox Terrier",
  "Treeing Walker Coonhound",
  "Vizsla",
  "Volpino Italiano",
  "Weimaraner",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "White Shepherd",
  "Wirehaired Pointing Griffon",
  "Wirehaired Vizsla",
  "Xoloitzcuintli",
  "Yorkshire Terrier"
];

const catBreeds = [
  "Abyssinian",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "American Wirehair",
  "Balinese",
  "Bengal",
  "Birman",
  "Bombay",
  "British Longhair",
  "British Shorthair",
  "Burmese",
  "Burmilla",
  "Chartreux",
  "Chausie",
  "Colorpoint Shorthair",
  "Cornish Rex",
  "Cymric",
  "Devon Rex",
  "Egyptian Mau",
  "European Shorthair",
  "Exotic Shorthair",
  "Havana Brown",
  "Highlander",
  "Himalayan",
  "Javanese",
  "Khao Manee",
  "Korat",
  "Kurilian Bobtail",
  "Laperm",
  "Lykoi",
  "Maine Coon",
  "Manx",
  "Munchkin",
  "Nebelung",
  "Norwegian Forest Cat",
  "Ocicat",
  "Oriental",
  "Persian",
  "Peterbald",
  "Ragamuffin",
  "Ragdoll",
  "Russian Blue",
  "Savannah",
  "Scottish Fold",
  "Selkirk Rex",
  "Serengeti",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Sokoke",
  "Sphynx",
  "Tonkinese",
  "Toyger",
  "Turkish Angora",
  "Turkish Van"
];

const dogChildren = dogBreeds.map(breed => ({
  value: breed.toLowerCase().replace(/ /g, '_'),
  label: breed,
}));

const catChildren = catBreeds.map(breed => ({
  value: breed.toLowerCase().replace(/ /g, '_'),
  label: breed,
}));

export const speciesOptions = [
  {
    value: "Dog",
    label: "Dog",
    children: dogChildren,
  },
  {
    value: "Cat",
    label: "Cat",
    children: catChildren,
  },
];

export const activityLevelOptions = [
  {
    value: "Low",
    label: "Low",
  },
  {
    value: "Moderate",
    label: "Moderate",
  },
  {
    value: "High",
    label: "High",
  },
  {
    value: "Performance",
    label: "Performance",
  },
];

export const lifeStageOptions = [
  {
    value: "Reproduction",
    label: "Reproduction",
  },
  {
    value: "Growth",
    label: "Growth",
  },
  {
    value: "Adult",
    label: "Adult",
  },
  {
    value: "Senior",
    label: "Senior",
  },
];